package com.alshevelev.alphapass.dto.entities

import android.support.annotation.DrawableRes
import com.alshevelev.alphapass.R
import com.alshevelev.alphapass.dto.enums.GroupIconType

/** */
data class AccountsGroupIcon(
    val id: Int,
    val type: GroupIconType,
    @DrawableRes val resId: Int) {

    companion object {
        val IconsLis = listOf<AccountsGroupIcon>(
            AccountsGroupIcon(1, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_adobe),
            AccountsGroupIcon(2, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_aol),
            AccountsGroupIcon(3, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_amazon),
            AccountsGroupIcon(4, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_yahoo),
            AccountsGroupIcon(5, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_amazon_kindle),
            AccountsGroupIcon(6, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_apple),
            AccountsGroupIcon(7, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_evernote),
            AccountsGroupIcon(8, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_google),
            AccountsGroupIcon(9, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_ozon),
            AccountsGroupIcon(10, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_yandex),
            AccountsGroupIcon(11, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_steam),
            AccountsGroupIcon(12, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_microsoft),
            AccountsGroupIcon(13, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_android),
            AccountsGroupIcon(14, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_ebay),
            AccountsGroupIcon(15, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_aliexpress),
            AccountsGroupIcon(16, GroupIconType.ONLINE_SERVICE, R.drawable.ic_group_youtube),

            AccountsGroupIcon(17, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_facebook),
            AccountsGroupIcon(18, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_instagram),
            AccountsGroupIcon(19, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_reddit),
            AccountsGroupIcon(20, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_vine),
            AccountsGroupIcon(21, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_tumblr),
            AccountsGroupIcon(22, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_googleplus),
            AccountsGroupIcon(23, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_vk),
            AccountsGroupIcon(24, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_meetup),
            AccountsGroupIcon(25, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_odnoklassniki),
            AccountsGroupIcon(26, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_twitter),
            AccountsGroupIcon(27, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_pinterest),
            AccountsGroupIcon(28, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_ask_fm),
            AccountsGroupIcon(29, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_flickr),
            AccountsGroupIcon(30, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_classmates),
            AccountsGroupIcon(31, GroupIconType.SOCIAL_NETWORK, R.drawable.ic_group_linkedin),

            AccountsGroupIcon(32, GroupIconType.MESSENGER, R.drawable.ic_group_facebook_messenger),
            AccountsGroupIcon(33, GroupIconType.MESSENGER, R.drawable.ic_group_whatsapp),
            AccountsGroupIcon(34, GroupIconType.MESSENGER, R.drawable.ic_group_wechat),
            AccountsGroupIcon(35, GroupIconType.MESSENGER, R.drawable.ic_group_line),
            AccountsGroupIcon(36, GroupIconType.MESSENGER, R.drawable.ic_group_viber),
            AccountsGroupIcon(37, GroupIconType.MESSENGER, R.drawable.ic_group_blackberry),
            AccountsGroupIcon(38, GroupIconType.MESSENGER, R.drawable.ic_group_telegram),
            AccountsGroupIcon(39, GroupIconType.MESSENGER, R.drawable.ic_group_kakaotalk),
            AccountsGroupIcon(40, GroupIconType.MESSENGER, R.drawable.ic_group_imo),
            AccountsGroupIcon(41, GroupIconType.MESSENGER, R.drawable.ic_group_skype),
            AccountsGroupIcon(42, GroupIconType.MESSENGER, R.drawable.ic_group_snapchat),
            AccountsGroupIcon(43, GroupIconType.MESSENGER, R.drawable.ic_group_kik),
            AccountsGroupIcon(44, GroupIconType.MESSENGER, R.drawable.ic_group_qq_mobile),
            AccountsGroupIcon(45, GroupIconType.MESSENGER, R.drawable.ic_group_iva),
            AccountsGroupIcon(46, GroupIconType.MESSENGER, R.drawable.ic_group_google_hangouts),
            AccountsGroupIcon(47, GroupIconType.MESSENGER, R.drawable.ic_group_slack),

            AccountsGroupIcon(48, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_paypal),
            AccountsGroupIcon(49, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_skrill),
            AccountsGroupIcon(50, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_2co_checkout),
            AccountsGroupIcon(51, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_ach_payments),
            AccountsGroupIcon(52, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_wepay),
            AccountsGroupIcon(53, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_authorize),
            AccountsGroupIcon(54, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_dwolla),
            AccountsGroupIcon(55, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_amazon_payments),
            AccountsGroupIcon(56, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_googlewallet),
            AccountsGroupIcon(57, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_webmoney),
            AccountsGroupIcon(58, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_yandex_money),
            AccountsGroupIcon(59, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_applepay),
            AccountsGroupIcon(60, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_payoneer),
            AccountsGroupIcon(61, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_payza),
            AccountsGroupIcon(62, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_venmo),
            AccountsGroupIcon(63, GroupIconType.ONLINE_PAYMENT_SOLUTION, R.drawable.ic_group_payu),

            AccountsGroupIcon(64, GroupIconType.ACTIVITY, R.drawable.ic_group_money),
            AccountsGroupIcon(65, GroupIconType.ACTIVITY, R.drawable.ic_group_money3),
            AccountsGroupIcon(66, GroupIconType.ACTIVITY, R.drawable.ic_group_mail),
            AccountsGroupIcon(67, GroupIconType.ACTIVITY, R.drawable.ic_group_mail2),
            AccountsGroupIcon(68, GroupIconType.ACTIVITY, R.drawable.ic_group_globe),
            AccountsGroupIcon(69, GroupIconType.ACTIVITY, R.drawable.ic_group_internet),
            AccountsGroupIcon(70, GroupIconType.ACTIVITY, R.drawable.ic_group_internet2),
            AccountsGroupIcon(71, GroupIconType.ACTIVITY, R.drawable.ic_group_health),
            AccountsGroupIcon(72, GroupIconType.ACTIVITY, R.drawable.ic_group_health2),
            AccountsGroupIcon(73, GroupIconType.ACTIVITY, R.drawable.ic_group_insurance),
            AccountsGroupIcon(74, GroupIconType.ACTIVITY, R.drawable.ic_group_bank),
            AccountsGroupIcon(75, GroupIconType.ACTIVITY, R.drawable.ic_group_auto),
            AccountsGroupIcon(76, GroupIconType.ACTIVITY, R.drawable.ic_group_games),
            AccountsGroupIcon(77, GroupIconType.ACTIVITY, R.drawable.ic_group_programming),
            AccountsGroupIcon(78, GroupIconType.ACTIVITY, R.drawable.ic_group_learning),
            AccountsGroupIcon(79, GroupIconType.ACTIVITY, R.drawable.ic_group_shopping),
            AccountsGroupIcon(80, GroupIconType.ACTIVITY, R.drawable.ic_group_music),
            AccountsGroupIcon(81, GroupIconType.ACTIVITY, R.drawable.ic_group_movie),
            AccountsGroupIcon(82, GroupIconType.ACTIVITY, R.drawable.ic_group_travelling),
            AccountsGroupIcon(83, GroupIconType.ACTIVITY, R.drawable.ic_group_taxi),
            AccountsGroupIcon(84, GroupIconType.ACTIVITY, R.drawable.ic_group_pets),
            AccountsGroupIcon(85, GroupIconType.ACTIVITY, R.drawable.ic_group_childs),
            AccountsGroupIcon(86, GroupIconType.ACTIVITY, R.drawable.ic_group_childs2),
            AccountsGroupIcon(87, GroupIconType.ACTIVITY, R.drawable.ic_group_weather),
            AccountsGroupIcon(88, GroupIconType.ACTIVITY, R.drawable.ic_group_security),
            AccountsGroupIcon(89, GroupIconType.ACTIVITY, R.drawable.ic_group_books),
            AccountsGroupIcon(90, GroupIconType.ACTIVITY, R.drawable.ic_group_magazines),
            AccountsGroupIcon(91, GroupIconType.ACTIVITY, R.drawable.ic_group_tools2),
            AccountsGroupIcon(92, GroupIconType.ACTIVITY, R.drawable.ic_group_stock),
            AccountsGroupIcon(93, GroupIconType.ACTIVITY, R.drawable.ic_group_painting),
            AccountsGroupIcon(94, GroupIconType.ACTIVITY, R.drawable.ic_group_entertainment),
            AccountsGroupIcon(95, GroupIconType.ACTIVITY, R.drawable.ic_group_entertainment2),
            AccountsGroupIcon(96, GroupIconType.ACTIVITY, R.drawable.ic_group_sport))
    }
}